package com.prgckwb.stationquiz.game

val keioLine = Line(
    lineName = "京王線",
    stations = listOf(
        Station("新宿"),
        Station("笹塚"),
        Station("代田橋"),
        Station("明大前"),
        Station("下高井戸"),
        Station("桜上水"),
        Station("上北沢"),
        Station("八幡山"),
        Station("芦花公園"),
        Station("千歳烏山"),
        Station("仙川"),
        Station("つつじヶ丘"),
        Station("柴崎"),
        Station("国領"),
        Station("布田"),
        Station("調布"),
        Station("西調布"),
        Station("飛田給"),
        Station("武蔵野台"),
        Station("多磨霊園"),
        Station("東府中"),
        Station("府中"),
        Station("分倍河原"),
        Station("中河原"),
        Station("聖蹟桜ヶ丘"),
        Station("百草園"),
        Station("高幡不動"),
        Station("南平"),
        Station("平山城址公園"),
        Station("長沼"),
        Station("北野"),
        Station("京王八王子"),
    )
)