package com.prgckwb.stationquiz.game

import androidx.compose.foundation.text.selection.LocalTextSelectionColors
import androidx.compose.ui.graphics.Color

// lineColorは Color(0xFF(カラーコード))

// exmaple
//  Line(
//      lineName = "つまみびしょ濡れライン",
//      lineColor = Color(0xFF90e200),
//         stations = listOf(
//              Station(),
//          )
//  ),

// JRグループ
val jrEastLines = listOf(
    Line(
        lineName = "JR東日本 高崎線",
        lineColor = Color(0xFFf68b1e),
        stations = listOf(
            Station("上野"),
            Station("尾久"),
            Station("赤羽"),
            Station("浦和"),
            Station("さいたま新都心"),
            Station("大宮"),
            Station("宮原"),
            Station("上尾"),
            Station("北上尾"),
            Station("桶川"),
            Station("北本"),
            Station("鴻巣"),
            Station("北鴻巣"),
            Station("吹上"),
            Station("行田"),
            Station("熊谷"),
            Station("籠原"),
            Station("深谷"),
            Station("岡部"),
            Station("本庄"),
            Station("神保原"),
            Station("新町"),
            Station("倉賀野"),
            Station("高崎"),
        )
    ),

    Line(
        lineName = "JR東日本 南武線",
        lineColor = Color(0xFFffd600),
        stations = listOf(
            Station("川崎"),
            Station("尻手"),
            Station("矢向"),
            Station("鹿島田"),
            Station("平間"),
            Station("向河原"),
            Station("武蔵小杉"),
            Station("武蔵中原"),
            Station("武蔵新城"),
            Station("武蔵溝ノ口"),
            Station("津田山"),
            Station("久地"),
            Station("宿河原"),
            Station("登戸"),
            Station("中野島"),
            Station("稲田堤"),
            Station("矢野口"),
            Station("稲城長沼"),
            Station("南多摩"),
            Station("府中本町"),
            Station("分倍河原"),
            Station("西府"),
            Station("谷保"),
            Station("矢川"),
            Station("西国立"),
            Station("立川"),
            Station("八丁畷"),
            Station("川崎新町"),
            Station("小田栄"),
            Station("浜川崎"),
        )
    ),

    Line(
        lineName = "JR東日本 湘南新宿ライン",
        lineColor = Color(0xFFe21f26),
        stations = listOf(
            Station("大宮"),
            Station("浦和"),
            Station("赤羽"),
            Station("池袋"),
            Station("新宿"),
            Station("渋谷"),
            Station("恵比寿"),
            Station("大崎"),
            Station("西大井"),
            Station("武蔵小杉"),
            Station("新川崎"),
            Station("横浜"),
            Station("保土ケ谷"),
            Station("東戸塚"),
            Station("戸塚"),
            Station("大船"),
        )
    ),

    Line(
        lineName = "JR東日本 埼京線",
        lineColor = Color(0xFF00ac9a),
        stations = listOf(
            Station("大崎"),
            Station("恵比寿"),
            Station("渋谷"),
            Station("新宿"),
            Station("池袋"),
            Station("板橋"),
            Station("十条"),
            Station("赤羽"),
            Station("北赤羽"),
            Station("浮間舟渡"),
            Station("戸田公園"),
            Station("戸田"),
            Station("北戸田"),
            Station("武蔵浦和"),
            Station("中浦和"),
            Station("南与野"),
            Station("与野本町"),
            Station("北与野"),
            Station("大宮"),
            Station("日進"),
            Station("指扇"),
            Station("南古谷"),
            Station("川越"),
        )
    ),

    Line(
        lineName = "JR東日本 山手線",
        lineColor = Color(0xFF99cc00),
        stations = listOf(
            Station("大崎"),
            Station("五反田"),
            Station("目黒"),
            Station("恵比寿"),
            Station("渋谷"),
            Station("原宿"),
            Station("代々木"),
            Station("新宿"),
            Station("新大久保"),
            Station("高田馬場"),
            Station("目白"),
            Station("池袋"),
            Station("大塚"),
            Station("巣鴨"),
            Station("駒込"),
            Station("田端"),
            Station("西日暮里"),
            Station("日暮里"),
            Station("鶯谷"),
            Station("上野"),
            Station("御徒町"),
            Station("秋葉原"),
            Station("神田"),
            Station("東京"),
            Station("有楽町"),
            Station("新橋"),
            Station("浜松町"),
            Station("田町"),
            Station("高輪ゲートウェイ"),
            Station("品川"),
        )
    ),

    ).sortedBy { it.lineName }
val jrHokkaidoLines = listOf(
    Line(
        lineName = "JR北海道 千歳線",
        lineColor = Color(0xFF0072BC),
        stations = listOf(
            Station("苫小牧"),
            Station("沼ノ端"),
            Station("植苗"),
            Station("美々"),
            Station("新千歳空港"),
            Station("南千歳"),
            Station("千歳"),
            Station("長都"),
            Station("サッポロビール庭園"),
            Station("恵庭"),
            Station("恵み野"),
            Station("島松"),
            Station("北広島"),
            Station("上野幌"),
            Station("新札幌"),
            Station("平和"),
            Station("白石"),
            Station("苗穂"),
            Station("札幌"),
        )
    ),
    Line(
        lineName = "JR北海道 室蘭本線",
        lineColor = Color(0xFF0072BC),
        stations = listOf(
            Station("長万部"),
            Station("静狩"),
            Station("小幌"),
            Station("礼文"),
            Station("大岸"),
            Station("豊浦"),
            Station("洞爺"),
            Station("有珠"),
            Station("長和"),
            Station("伊達紋別"),
            Station("北舟岡"),
            Station("稀府"),
            Station("黄金"),
            Station("崎守"),
            Station("本輪西"),
            Station("室蘭"),
            Station("母恋"),
            Station("御崎"),
            Station("輪西"),
            Station("東室蘭"),
            Station("鷲別"),
            Station("幌別"),
            Station("富浦"),
            Station("登別"),
            Station("虎杖浜"),
            Station("竹浦"),
            Station("北吉原"),
            Station("萩野"),
            Station("白老"),
            Station("社台"),
            Station("錦岡"),
            Station("糸井"),
            Station("青葉"),
            Station("苫小牧"),
            Station("沼ノ端"),
            Station("遠浅"),
            Station("早来"),
            Station("安平"),
            Station("追分"),
            Station("三川"),
            Station("古山"),
            Station("由仁"),
            Station("栗山"),
            Station("栗丘"),
            Station("栗沢"),
            Station("志文"),
            Station("岩見沢"),
        )
    ),
    Line(
        lineName = "JR北海道 函館本線\n（函館〜長万部）",
        lineColor = Color(0xFF0072BC),
        stations = listOf(
            Station("函館"),
            Station("五稜郭"),
            Station("桔梗"),
            Station("大中山"),
            Station("七飯"),
            Station("新函館北斗"),
            Station("仁山"),
            Station("大沼"),
            Station("大沼公園"),
            Station("赤井川"),
            Station("駒ケ岳"),
            Station("東山"),
            Station("姫川"),
            Station("池田園"),
            Station("流山温泉"),
            Station("銚子口"),
            Station("鹿部"),
            Station("渡島沼尻"),
            Station("渡島砂原"),
            Station("掛澗"),
            Station("尾白内"),
            Station("東森"),
            Station("森"),
            Station("桂川"),
            Station("石谷"),
            Station("本石倉"),
            Station("石倉"),
            Station("落部"),
            Station("野田生"),
            Station("山越"),
            Station("八雲"),
            Station("鷲ノ巣"),
            Station("山崎"),
            Station("黒岩"),
            Station("北豊津"),
            Station("国縫"),
            Station("中ノ沢"),
            Station("長万部"),
        )
    ),
    Line(
        lineName = "JR北海道 函館本線\n（長万部〜札幌）",
        lineColor = Color(0xFFed1c23),
        stations = listOf(
            Station("長万部"),
            Station("二股"),
            Station("蕨岱"),
            Station("黒松内"),
            Station("熱郛"),
            Station("目名"),
            Station("蘭越"),
            Station("昆布"),
            Station("ニセコ"),
            Station("比羅夫"),
            Station("倶知安"),
            Station("小沢"),
            Station("銀山"),
            Station("然別"),
            Station("仁木"),
            Station("余市"),
            Station("蘭島"),
            Station("塩谷"),
            Station("小樽"),
            Station("南小樽"),
            Station("小樽築港"),
            Station("朝里"),
            Station("銭函"),
            Station("ほしみ"),
            Station("星置"),
            Station("稲穂"),
            Station("手稲"),
            Station("稲積公園"),
            Station("発寒"),
            Station("発寒中央"),
            Station("琴似"),
            Station("桑園"),
            Station("札幌"),
        )
    ),
    Line(
        lineName = "JR北海道 函館本線\n（札幌〜旭川）",
        lineColor = Color(0xFFf7931d),
        stations = listOf(
            Station("札幌"),
            Station("苗穂"),
            Station("白石"),
            Station("厚別"),
            Station("森林公園"),
            Station("大麻"),
            Station("野幌"),
            Station("高砂"),
            Station("江別"),
            Station("豊幌"),
            Station("幌向"),
            Station("上幌向"),
            Station("岩見沢"),
            Station("峰延"),
            Station("光珠内"),
            Station("美唄"),
            Station("茶志内"),
            Station("奈井江"),
            Station("豊沼"),
            Station("砂川"),
            Station("滝川"),
            Station("江部乙"),
            Station("妹背牛"),
            Station("深川"),
            Station("納内"),
            Station("伊納"),
            Station("近文"),
            Station("旭川"),
        )
    ),

    Line(
        lineName = "JR北海道 石北本線",
        lineColor = Color(0xFFf7931d),
        stations = listOf(
            Station("旭川"),
            Station("旭川四条"),
            Station("新旭川"),
            Station("南永山"),
            Station("東旭川"),
            Station("北日ノ出"),
            Station("桜岡"),
            Station("当麻"),
            Station("将軍山"),
            Station("伊香牛"),
            Station("愛別"),
            Station("中愛別"),
            Station("愛山"),
            Station("安足間"),
            Station("東雲"),
            Station("上川"),
            Station("上白滝"),
            Station("白滝"),
            Station("旧白滝"),
            Station("下白滝"),
            Station("丸瀬布"),
            Station("瀬戸瀬"),
            Station("遠軽"),
            Station("安国"),
            Station("生野"),
            Station("生田原"),
            Station("金華"),
            Station("西留辺蘂"),
            Station("留辺蘂"),
            Station("相内"),
            Station("東相内"),
            Station("西北見"),
            Station("北見"),
            Station("柏陽"),
            Station("愛し野"),
            Station("端野"),
            Station("緋牛内"),
            Station("美幌"),
            Station("西女満別"),
            Station("女満別"),
            Station("呼人"),
            Station("網走"),
        )
    )
).sortedBy { it.lineName }
val jrTokaiLines = listOf(
    Line(
        lineName = "JR東海 東海道本線\n（熱海〜浜松）",
        lineColor = Color(0xFFf57615),
        stations = listOf(
            Station("熱海"),
            Station("函南"),
            Station("三島"),
            Station("沼津"),
            Station("片浜"),
            Station("原"),
            Station("東田子の浦"),
            Station("吉原"),
            Station("富士"),
            Station("富士川"),
            Station("新蒲原"),
            Station("蒲原"),
            Station("由比"),
            Station("興津"),
            Station("清水"),
            Station("草薙"),
            Station("東静岡"),
            Station("静岡"),
            Station("安倍川"),
            Station("用宗"),
            Station("焼津"),
            Station("西焼津"),
            Station("藤枝"),
            Station("六合"),
            Station("島田"),
            Station("金谷"),
            Station("菊川"),
            Station("掛川"),
            Station("愛野"),
            Station("袋井"),
            Station("御厨"),
            Station("磐田"),
            Station("豊田町"),
            Station("天竜川"),
            Station("浜松"),
        )
    ),
    Line(
        lineName = "JR東海 東海道本線\n（浜松〜岐阜）",
        lineColor = Color(0xFFf57615),
        stations = listOf(
            Station("浜松"),
            Station("高塚"),
            Station("舞阪"),
            Station("弁天島"),
            Station("新居町"),
            Station("鷲津"),
            Station("新所原"),
            Station("二川"),
            Station("豊橋"),
            Station("西小坂井"),
            Station("愛知御津"),
            Station("三河大塚"),
            Station("三河三谷"),
            Station("蒲郡"),
            Station("三河塩津"),
            Station("三ケ根"),
            Station("幸田"),
            Station("相見"),
            Station("岡崎"),
            Station("西岡崎"),
            Station("安城"),
            Station("三河安城"),
            Station("東刈谷"),
            Station("野田新町"),
            Station("刈谷"),
            Station("逢妻"),
            Station("大府"),
            Station("共和"),
            Station("南大高"),
            Station("大高"),
            Station("笠寺"),
            Station("熱田"),
            Station("金山"),
            Station("尾頭橋"),
            Station("名古屋"),
            Station("枇杷島"),
            Station("清洲"),
            Station("稲沢"),
            Station("尾張一宮"),
            Station("木曽川"),
            Station("岐阜"),
        )
    ),
    Line(
        lineName = "JR東海 東海道本線\n（岐阜～美濃赤坂・米原）",
        lineColor = Color(0xFFf57615),
        stations = listOf(
            Station("岐阜"),
            Station("西岐阜"),
            Station("穂積"),
            Station("大垣"),
            Station("荒尾"),
            Station("美濃赤坂"),
            Station("垂井"),
            Station("関ケ原"),
            Station("柏原"),
            Station("近江長岡"),
            Station("醒ケ井"),
            Station("米原"),
        )
    ),
).sortedBy { it.lineName }
val jrWestLines = listOf(
    Line(
        lineName = "JR西日本 大阪環状線",
        lineColor = Color(0xFFe73042),
        stations = listOf(
            Station("天王寺"),
            Station("新今宮"),
            Station("今宮"),
            Station("芦原橋"),
            Station("大正"),
            Station("弁天町"),
            Station("西九条"),
            Station("野田"),
            Station("福島"),
            Station("大阪"),
            Station("天満"),
            Station("桜ノ宮"),
            Station("京橋"),
            Station("大阪城公園"),
            Station("森ノ宮"),
            Station("玉造"),
            Station("鶴橋"),
            Station("桃谷"),
            Station("寺田町"),
        )
    ),
    Line(
        lineName = "JR西日本 宝塚線",
        lineColor = Color(0xFFfcc800),
        stations = listOf(
            Station("新大阪"),
            Station("大阪"),
            Station("尼崎"),
            Station("塚口"),
            Station("猪名寺"),
            Station("伊丹"),
            Station("北伊丹"),
            Station("川西池田"),
            Station("中山寺"),
            Station("宝塚"),
            Station("生瀬"),
            Station("西宮名塩"),
            Station("武田尾"),
            Station("道場"),
            Station("三田"),
            Station("新三田"),
            Station("広野"),
            Station("相野"),
            Station("藍本"),
            Station("草野"),
            Station("古市"),
            Station("南矢代"),
            Station("篠山口"),
        )
    ),
    Line(
        lineName = "JR西日本 福知山線\n(篠山口～福知山)",
        lineColor = Color(0xFFfcc800),
        stations = listOf(
            Station("篠山口"),
            Station("丹波大山"),
            Station("下滝"),
            Station("谷川"),
            Station("柏原"),
            Station("石生"),
            Station("黒井"),
            Station("市島"),
            Station("丹波竹田"),
            Station("福知山"),
        )
    ),
    Line(
        lineName = "JR西日本 東西線",
        lineColor = Color(0xFFe73082),
        stations = listOf(
            Station("京橋"),
            Station("大阪城北詰"),
            Station("大阪天満宮"),
            Station("北新地"),
            Station("新福島"),
            Station("海老江"),
            Station("御幣島"),
            Station("加島"),
            Station("尼崎"),
        )
    ),
).sortedBy { it.lineName }
val jrShikokuLines = listOf(
    Line(
        lineName = "JR四国 予讃線",
        lineColor = Color(0xFFFF9900),
        stations = listOf(
            Station("高松"),
            Station("香西"),
            Station("鬼無"),
            Station("端岡"),
            Station("国分"),
            Station("讃岐府中"),
            Station("鴨川"),
            Station("八十場"),
            Station("坂出"),
            Station("宇多津"),
            Station("丸亀"),
            Station("讃岐塩屋"),
            Station("多度津"),
            Station("海岸寺"),
            Station("津島ノ宮"),
            Station("詫間"),
            Station("みの"),
            Station("高瀬"),
            Station("比地大"),
            Station("本山"),
            Station("観音寺"),
            Station("豊浜"),
            Station("箕浦"),
            Station("川之江"),
            Station("伊予三島"),
            Station("伊予寒川"),
            Station("赤星"),
            Station("伊予土居"),
            Station("関川"),
            Station("多喜浜"),
            Station("新居浜"),
            Station("中萩"),
            Station("伊予西条"),
            Station("石鎚山"),
            Station("伊予氷見"),
            Station("伊予小松"),
            Station("玉之江"),
            Station("壬生川"),
            Station("伊予三芳"),
            Station("伊予桜井"),
            Station("伊予富田"),
            Station("今治"),
            Station("波止浜"),
            Station("波方"),
            Station("大西"),
            Station("伊予亀岡"),
            Station("菊間"),
            Station("浅海"),
            Station("大浦"),
            Station("伊予北条"),
            Station("柳原"),
            Station("粟井"),
            Station("光洋台"),
            Station("堀江"),
            Station("伊予和気"),
            Station("三津浜"),
            Station("松山"),
        )
    ),
    Line(
        lineName = "JR四国 土讃線",
        lineColor = Color(0xFFE25885),
        stations = listOf(
            Station("多度津"),
            Station("金蔵寺"),
            Station("善通寺"),
            Station("琴平"),
            Station("塩入"),
            Station("黒川"),
            Station("讃岐財田"),
            Station("坪尻"),
            Station("箸蔵"),
            Station("佃"),
            Station("阿波池田"),
            Station("三縄"),
            Station("祖谷口"),
            Station("阿波川口"),
            Station("小歩危"),
            Station("大歩危"),
            Station("土佐岩原"),
            Station("豊永"),
            Station("大田口"),
            Station("土佐穴内"),
            Station("大杉"),
            Station("土佐北川"),
            Station("角茂谷"),
            Station("繁藤"),
            Station("新改"),
            Station("土佐山田"),
            Station("山田西町"),
            Station("土佐長岡"),
            Station("後免"),
            Station("土佐大津"),
            Station("布師田"),
            Station("土佐一宮"),
            Station("薊野"),
            Station("高知"),
            Station("入明"),
            Station("円行寺口"),
            Station("旭"),
            Station("高知商業前"),
            Station("朝倉"),
            Station("枝川"),
            Station("伊野"),
            Station("波川"),
            Station("小村神社前"),
            Station("日下"),
            Station("岡花"),
            Station("土佐加茂"),
            Station("西佐川"),
            Station("佐川"),
            Station("襟野々"),
            Station("斗賀野"),
            Station("吾桑"),
            Station("多ノ郷"),
            Station("大間"),
            Station("須崎"),
            Station("土佐新荘"),
            Station("安和"),
            Station("土佐久礼"),
            Station("影野"),
            Station("六反地"),
            Station("仁井田"),
            Station("窪川"),
        )
    ),
    Line(
        lineName = "JR四国 高徳線",
        lineColor = Color(0xFF99CC00),
        stations = listOf(
            Station("高松"),
            Station("昭和町"),
            Station("栗林公園北口"),
            Station("栗林"),
            Station("木太町"),
            Station("屋島"),
            Station("古高松南"),
            Station("八栗口"),
            Station("讃岐牟礼"),
            Station("志度"),
            Station("オレンジタウン"),
            Station("造田"),
            Station("神前"),
            Station("讃岐津田"),
            Station("鶴羽"),
            Station("丹生"),
            Station("三本松"),
            Station("讃岐白鳥"),
            Station("引田"),
            Station("讃岐相生"),
            Station("阿波大宮"),
            Station("板野"),
            Station("阿波川端"),
            Station("板東"),
            Station("池谷"),
            Station("勝瑞"),
            Station("吉成"),
            Station("佐古"),
            Station("徳島"),
        )
    ),
    Line(
        lineName = "JR四国 徳島線\n（よしの川ブルーライン）",
        lineColor = Color(0xFF008080),
        stations = listOf(
            Station("徳島"),
            Station("佐古"),
            Station("蔵本"),
            Station("鮎喰"),
            Station("府中"),
            Station("石井"),
            Station("下浦"),
            Station("牛島"),
            Station("麻植塚"),
            Station("鴨島"),
            Station("西麻植"),
            Station("阿波川島"),
            Station("学"),
            Station("山瀬"),
            Station("阿波山川"),
            Station("川田"),
            Station("穴吹"),
            Station("小島"),
            Station("貞光"),
            Station("阿波半田"),
            Station("江口"),
            Station("三加茂"),
            Station("阿波加茂"),
            Station("辻"),
            Station("佃"),
            Station("阿波池田"),
        )
    ),
    Line(
        lineName = "JR四国 予土線\n（しまんとグリーンライン）",
        lineColor = Color(0xFF339966),
        stations = listOf(
            Station("窪川"),
            Station("若井"),
            Station("家地川"),
            Station("打井川"),
            Station("土佐大正"),
            Station("土佐昭和"),
            Station("十川"),
            Station("半家"),
            Station("江川崎"),
            Station("西ケ方"),
            Station("真土"),
            Station("吉野生"),
            Station("松丸"),
            Station("出目"),
            Station("近永"),
            Station("深田"),
            Station("大内"),
            Station("二名"),
            Station("伊予宮野下"),
            Station("務田"),
            Station("北宇和島"),
            Station("宇和島"),
        )
    ),
    Line(
        lineName = "JR四国 鳴門線",
        lineColor = Color(0xFF993366),
        stations = listOf(
            Station("鳴門"),
            Station("撫養"),
            Station("金比羅前"),
            Station("教会前"),
            Station("立道"),
            Station("阿波大谷"),
            Station("池谷"),
        )
    ),
    Line(
        lineName = "JR四国 牟岐線",
        lineColor = Color(0xFF00FFFF),
        stations = listOf(
            Station("徳島"),
            Station("阿波富田"),
            Station("二軒屋"),
            Station("文化の森"),
            Station("地蔵橋"),
            Station("中田"),
            Station("南小松島"),
            Station("阿波赤石"),
            Station("立江"),
            Station("羽ノ浦"),
            Station("西原"),
            Station("阿波中島"),
            Station("阿南"),
            Station("見能林"),
            Station("阿波橘"),
            Station("桑野"),
            Station("新野"),
            Station("阿波福井"),
            Station("由岐"),
            Station("田井ノ浜"),
            Station("木岐"),
            Station("北河内"),
            Station("日和佐"),
            Station("山河内"),
            Station("辺川"),
            Station("牟岐"),
            Station("鯖瀬"),
            Station("浅川"),
            Station("阿波海南"),
        )
    ),
).sortedBy { it.lineName }
val jrKyusyuLines = listOf(
    Line(
        lineName = "JR九州 鹿児島本線\n(下関・門司港～博多)",
        lineColor = Color(0xFFee3d49),
        stations = listOf(
            Station("下関"),
            Station("門司港"),
            Station("小森江"),
            Station("門司"),
            Station("小倉"),
            Station("西小倉"),
            Station("九州工大前"),
            Station("戸畑"),
            Station("枝光"),
            Station("スペースワールド"),
            Station("八幡"),
            Station("黒崎"),
            Station("陣原"),
            Station("折尾"),
            Station("水巻"),
            Station("遠賀川"),
            Station("海老津"),
            Station("教育大前"),
            Station("赤間"),
            Station("東郷"),
            Station("東福間"),
            Station("福間"),
            Station("千鳥"),
            Station("古賀"),
            Station("ししぶ"),
            Station("新宮中央"),
            Station("福工大前"),
            Station("九産大前"),
            Station("香椎"),
            Station("千早"),
            Station("箱崎"),
            Station("吉塚"),
            Station("博多"),
        )
    ),
    Line(
        lineName = "JR九州 鹿児島本線\n(博多～八代)",
        lineColor = Color(0xFFee3d49),
        stations = listOf(
            Station("博多"),
            Station("竹下"),
            Station("笹原"),
            Station("南福岡"),
            Station("春日"),
            Station("大野城"),
            Station("水城"),
            Station("都府楼南"),
            Station("二日市"),
            Station("天拝山"),
            Station("原田"),
            Station("けやき台"),
            Station("基山"),
            Station("弥生が丘"),
            Station("田代"),
            Station("鳥栖"),
            Station("肥前旭"),
            Station("久留米"),
            Station("荒木"),
            Station("西牟田"),
            Station("羽犬塚"),
            Station("筑後船小屋"),
            Station("瀬高"),
            Station("南瀬高"),
            Station("渡瀬"),
            Station("吉野"),
            Station("銀水"),
            Station("大牟田"),
            Station("荒尾"),
            Station("南荒尾"),
            Station("長洲"),
            Station("大野下"),
            Station("玉名"),
            Station("肥後伊倉"),
            Station("木葉"),
            Station("田原坂"),
            Station("植木"),
            Station("西里"),
            Station("崇城大学前"),
            Station("上熊本"),
            Station("熊本"),
            Station("西熊本"),
            Station("川尻"),
            Station("富合"),
            Station("宇土"),
            Station("松橋"),
            Station("小川"),
            Station("有佐"),
            Station("千丁"),
            Station("新八代"),
            Station("八代"),
        )
    ),
    Line(
        lineName = "JR九州 鹿児島本線\n(川内～鹿児島)",
        lineColor = Color(0xFFee3d49),
        stations = listOf(
            Station("博多"),
            Station("竹下"),
            Station("笹原"),
            Station("南福岡"),
            Station("春日"),
            Station("大野城"),
            Station("水城"),
            Station("都府楼南"),
            Station("二日市"),
            Station("天拝山"),
            Station("原田"),
            Station("けやき台"),
            Station("基山"),
            Station("弥生が丘"),
            Station("田代"),
            Station("鳥栖"),
            Station("肥前旭"),
            Station("久留米"),
            Station("荒木"),
            Station("西牟田"),
            Station("羽犬塚"),
            Station("筑後船小屋"),
            Station("瀬高"),
            Station("南瀬高"),
            Station("渡瀬"),
            Station("吉野"),
            Station("銀水"),
            Station("大牟田"),
            Station("荒尾"),
            Station("南荒尾"),
            Station("長洲"),
            Station("大野下"),
            Station("玉名"),
            Station("肥後伊倉"),
            Station("木葉"),
            Station("田原坂"),
            Station("植木"),
            Station("西里"),
            Station("崇城大学前"),
            Station("上熊本"),
            Station("熊本"),
            Station("西熊本"),
            Station("川尻"),
            Station("富合"),
            Station("宇土"),
            Station("松橋"),
            Station("小川"),
            Station("有佐"),
            Station("千丁"),
            Station("新八代"),
            Station("八代"),
        )
    ),
).sortedBy { it.lineName }

//　大手私鉄
val toeiChikatetsuLines = listOf(
    Line(
        lineName = "都営地下鉄 浅草線",
        lineColor = Color(0xFFE85298),
        stations = listOf(
            Station("西馬込"),
            Station("馬込"),
            Station("中延"),
            Station("戸越"),
            Station("五反田"),
            Station("高輪台"),
            Station("泉岳寺"),
            Station("三田"),
            Station("大門"),
            Station("新橋"),
            Station("東銀座"),
            Station("宝町"),
            Station("日本橋"),
            Station("人形町"),
            Station("東日本橋"),
            Station("浅草橋"),
            Station("蔵前"),
            Station("浅草"),
            Station("本所吾妻橋"),
            Station("押上（スカイツリー前）"),
        )
    ),

    Line(
        lineName = "都営地下鉄 三田線",
        lineColor = Color(0xFF0079c2),
        stations = listOf(
            Station("目黒"),
            Station("白金台"),
            Station("白金高輪"),
            Station("三田"),
            Station("芝公園"),
            Station("御成門"),
            Station("内幸町"),
            Station("日比谷"),
            Station("大手町"),
            Station("神保町"),
            Station("水道橋"),
            Station("春日"),
            Station("白山"),
            Station("千石"),
            Station("巣鴨"),
            Station("西巣鴨"),
            Station("新板橋"),
            Station("板橋区役所前"),
            Station("板橋本町"),
            Station("本蓮沼"),
            Station("志村坂上"),
            Station("志村三丁目"),
            Station("蓮根"),
            Station("西台"),
            Station("高島平"),
            Station("新高島平"),
            Station("西高島平"),
        )
    ),

    Line(
        lineName = "都営地下鉄 新宿線",
        lineColor = Color(0xFF6cbb5a),
        stations = listOf(
            Station("新宿"),
            Station("新宿三丁目"),
            Station("曙橋"),
            Station("市ヶ谷"),
            Station("九段下"),
            Station("神保町"),
            Station("小川町"),
            Station("岩本町"),
            Station("馬喰横山"),
            Station("浜町"),
            Station("森下"),
            Station("菊川"),
            Station("住吉"),
            Station("西大島"),
            Station("大島"),
            Station("東大島"),
            Station("船堀"),
            Station("一之江"),
            Station("瑞江"),
            Station("篠崎"),
            Station("本八幡"),
        )
    ),

    Line(
        lineName = "都営地下鉄 大江戸線",
        lineColor = Color(0xFFb6007a),
        stations = listOf(
            Station("都庁前"),
            Station("新宿西口"),
            Station("東新宿"),
            Station("若松河田"),
            Station("牛込柳町"),
            Station("牛込神楽坂"),
            Station("飯田橋"),
            Station("春日"),
            Station("本郷三丁目"),
            Station("上野御徒町"),
            Station("新御徒町"),
            Station("蔵前"),
            Station("両国"),
            Station("森下"),
            Station("清澄白河"),
            Station("門前仲町"),
            Station("月島"),
            Station("勝どき"),
            Station("築地市場"),
            Station("汐留"),
            Station("大門"),
            Station("赤羽橋"),
            Station("麻布十番"),
            Station("六本木"),
            Station("青山一丁目"),
            Station("国立競技場"),
            Station("代々木"),
            Station("新宿"),
            Station("西新宿五丁目"),
            Station("中野坂上"),
            Station("東中野"),
            Station("中井"),
            Station("落合南長崎"),
            Station("新江古田"),
            Station("練馬"),
            Station("豊島園"),
            Station("練馬春日町"),
            Station("光が丘"),
        )
    ),

    )
val tokyoMetroLines = listOf(
//    東京メトロ
    Line(
        lineName = "東京メトロ 銀座線",
        lineColor = Color(0xFFFF9500),
        stations = listOf(
            Station("浅草"),
            Station("田原町"),
            Station("稲荷町"),
            Station("上野"),
            Station("上野広小路"),
            Station("末広町"),
            Station("神田"),
            Station("三越前"),
            Station("日本橋"),
            Station("京橋"),
            Station("銀座"),
            Station("新橋"),
            Station("虎ノ門"),
            Station("溜池山王"),
            Station("赤坂見附"),
            Station("青山一丁目"),
            Station("外苑前"),
            Station("表参道"),
            Station("渋谷"),
        )
    ),

    Line(
        lineName = "東京メトロ 丸の内線",
        lineColor = Color(0xFFF62E36),
        stations = listOf(
            Station("池袋"),
            Station("新大塚"),
            Station("茗荷谷"),
            Station("後楽園"),
            Station("本郷三丁目"),
            Station("御茶ノ水"),
            Station("淡路町"),
            Station("大手町"),
            Station("東京"),
            Station("銀座"),
            Station("霞ケ関"),
            Station("国会議事堂前"),
            Station("赤坂見附"),
            Station("四ツ谷"),
            Station("四谷三丁目"),
            Station("新宿御苑前"),
            Station("新宿三丁目"),
            Station("新宿"),
            Station("西新宿"),
            Station("中野坂上"),
            Station("新中野"),
            Station("東高円寺"),
            Station("新高円寺"),
            Station("南阿佐ケ谷"),
            Station("荻窪"),
            Station("中野新橋"),
            Station("中野富士見町"),
            Station("方南町"),
        )
    ),

    Line(
        lineName = "東京メトロ 日比谷線",
        lineColor = Color(0xFFB5B5AC),
        stations = listOf(
            Station("北千住"),
            Station("南千住"),
            Station("三ノ輪"),
            Station("入谷"),
            Station("上野"),
            Station("仲御徒町"),
            Station("秋葉原"),
            Station("小伝馬町"),
            Station("人形町"),
            Station("茅場町"),
            Station("八丁堀"),
            Station("築地"),
            Station("東銀座"),
            Station("銀座"),
            Station("日比谷"),
            Station("霞ケ関"),
            Station("虎ノ門ヒルズ"),
            Station("神谷町"),
            Station("六本木"),
            Station("広尾"),
            Station("恵比寿"),
            Station("中目黒"),
        )
    ),


    Line(
        lineName = "東京メトロ 東西線",
        lineColor = Color(0xFF009BBF),
        stations = listOf(
            Station("中野"),
            Station("落合"),
            Station("高田馬場"),
            Station("早稲田"),
            Station("神楽坂"),
            Station("飯田橋"),
            Station("九段下"),
            Station("竹橋"),
            Station("大手町"),
            Station("日本橋"),
            Station("茅場町"),
            Station("門前仲町"),
            Station("木場"),
            Station("東陽町"),
            Station("南砂町"),
            Station("西葛西"),
            Station("葛西"),
            Station("浦安"),
            Station("南行徳"),
            Station("行徳"),
            Station("妙典"),
            Station("原木中山"),
            Station("西船橋"),
        )
    ),

    Line(
        lineName = "東京メトロ 千代田線",
        lineColor = Color(0xFF00BB85),
        stations = listOf(
            Station("北綾瀬"),
            Station("綾瀬"),
            Station("北千住"),
            Station("町屋"),
            Station("西日暮里"),
            Station("千駄木"),
            Station("根津"),
            Station("湯島"),
            Station("新御茶ノ水"),
            Station("大手町"),
            Station("二重橋前"),
            Station("日比谷"),
            Station("霞ケ関"),
            Station("国会議事堂前"),
            Station("赤坂"),
            Station("乃木坂"),
            Station("表参道"),
            Station("明治神宮前〈原宿〉"),
            Station("代々木公園"),
            Station("代々木上原"),
        )
    ),

    Line(
        lineName = "東京メトロ 有楽町線",
        lineColor = Color(0xFFC1A470),
        stations = listOf(
            Station("和光市"),
            Station("地下鉄成増"),
            Station("地下鉄赤塚"),
            Station("平和台"),
            Station("氷川台"),
            Station("小竹向原"),
            Station("千川"),
            Station("要町"),
            Station("池袋"),
            Station("東池袋"),
            Station("護国寺"),
            Station("江戸川橋"),
            Station("飯田橋"),
            Station("市ケ谷"),
            Station("麹町"),
            Station("永田町"),
            Station("桜田門"),
            Station("有楽町"),
            Station("銀座一丁目"),
            Station("新富町"),
            Station("月島"),
            Station("豊洲"),
            Station("辰巳"),
            Station("新木場"),

            )
    ),

    Line(
        lineName = "東京メトロ 半蔵門線",
        lineColor = Color(0xFF8F76D6),
        stations = listOf(
            Station("渋谷"),
            Station("表参道"),
            Station("青山一丁目"),
            Station("永田町"),
            Station("半蔵門"),
            Station("九段下"),
            Station("神保町"),
            Station("大手町"),
            Station("三越前"),
            Station("水天宮前"),
            Station("清澄白河"),
            Station("住吉"),
            Station("錦糸町"),
            Station("押上〈スカイツリー前〉"),
        )
    ),

    Line(
        lineName = "東京メトロ 南北線",
        lineColor = Color(0xFF00AC9B),
        stations = listOf(
            Station("赤羽岩淵"),
            Station("志茂"),
            Station("王子神谷"),
            Station("王子"),
            Station("西ケ原"),
            Station("駒込"),
            Station("本駒込"),
            Station("東大前"),
            Station("後楽園"),
            Station("飯田橋"),
            Station("市ケ谷"),
            Station("四ツ谷"),
            Station("永田町"),
            Station("溜池山王"),
            Station("六本木一丁目"),
            Station("麻布十番"),
            Station("白金高輪"),
            Station("白金台"),
            Station("目黒"),
        )
    ),

    Line(
        lineName = "東京メトロ 副都心線",
        lineColor = Color(0xFF9C5E31),
        stations = listOf(
            Station("和光市"),
            Station("地下鉄成増"),
            Station("地下鉄赤塚"),
            Station("平和台"),
            Station("氷川台"),
            Station("小竹向原"),
            Station("千川"),
            Station("要町"),
            Station("池袋"),
            Station("雑司が谷"),
            Station("西早稲田"),
            Station("東新宿"),
            Station("新宿三丁目"),
            Station("北参道"),
            Station("明治神宮前〈原宿〉"),
            Station("渋谷"),
        )
    ),
).sortedBy { it.lineName }
val keioLines = listOf(
    Line(
        lineName = "京王電鉄 京王線",
        lineColor = Color(0xFFdd0076),
        stations = listOf(
            Station("新宿"),
            Station("笹塚"),
            Station("代田橋"),
            Station("明大前"),
            Station("下高井戸"),
            Station("桜上水"),
            Station("上北沢"),
            Station("八幡山"),
            Station("芦花公園"),
            Station("千歳烏山"),
            Station("仙川"),
            Station("つつじヶ丘"),
            Station("柴崎"),
            Station("国領"),
            Station("布田"),
            Station("調布"),
            Station("西調布"),
            Station("飛田給"),
            Station("武蔵野台"),
            Station("多磨霊園"),
            Station("東府中"),
            Station("府中"),
            Station("分倍河原"),
            Station("中河原"),
            Station("聖蹟桜ヶ丘"),
            Station("百草園"),
            Station("高幡不動"),
            Station("南平"),
            Station("平山城址公園"),
            Station("長沼"),
            Station("北野"),
            Station("京王八王子"),
        )
    ),
    Line(
        lineName = "京王電鉄 京王相模原線",
        lineColor = Color(0xFFdd0076),
        stations = listOf(
            Station("調布"),
            Station("京王多摩川"),
            Station("京王稲田堤"),
            Station("京王よみうりランド"),
            Station("稲城"),
            Station("若葉台"),
            Station("京王永山"),
            Station("京王多摩センター"),
            Station("京王堀之内"),
            Station("南大沢"),
            Station("多摩境"),
            Station("橋本"),
        )
    ),
    Line(
        lineName = "京王電鉄 京王高尾線",
        lineColor = Color(0xFFdd0076),
        stations = listOf(
            Station("北野"),
            Station("京王片倉"),
            Station("山田"),
            Station("めじろ台"),
            Station("狭間"),
            Station("高尾"),
            Station("高尾山口"),
        )
    ),

//    二択だとバグが出る
    Line(
        lineName = "京王電鉄 京王競馬場線",
        lineColor = Color(0xFFdd0076),
        stations = listOf(
            Station("東府中"),
            Station("府中競馬正門前"),
            Station("東府中"),
            Station("府中競馬正門前"),
        )
    ),
    Line(
        lineName = "京王電鉄 京王井の頭線",
        lineColor = Color(0xFF000088),
        stations = listOf(
            Station("渋谷"),
            Station("神泉"),
            Station("駒場東大前"),
            Station("池ノ上"),
            Station("下北沢"),
            Station("新代田"),
            Station("東松原"),
            Station("明大前"),
            Station("永福町"),
            Station("西永福"),
            Station("浜田山"),
            Station("高井戸"),
            Station("富士見ヶ丘"),
            Station("久我山"),
            Station("三鷹台"),
            Station("井の頭公園"),
            Station("吉祥寺"),
        )
    ),
    Line(
        lineName = "京王電鉄 京王新線",
        lineColor = Color(0xFFdd0076),
        stations = listOf(
            Station("新線新宿"),
            Station("笹塚"),
            Station("初台"),
            Station("幡ヶ谷"),
        )
    ),

    ).sortedBy { it.lineName }
val odakyuLines = listOf(
    Line(
        lineName = "小田急電鉄 小田急線",
        lineColor = Color(0xFF2288cc),
        stations = listOf(
            Station("新宿"),
            Station("南新宿"),
            Station("参宮橋"),
            Station("代々木八幡"),
            Station("代々木上原"),
            Station("東北沢"),
            Station("下北沢"),
            Station("世田谷代田"),
            Station("梅ヶ丘"),
            Station("豪徳寺"),
            Station("経堂"),
            Station("千歳船橋"),
            Station("祖師ヶ谷大蔵"),
            Station("成城学園前"),
            Station("喜多見"),
            Station("狛江"),
            Station("和泉多摩川"),
            Station("登戸"),
            Station("向ヶ丘遊園"),
            Station("生田"),
            Station("読売ランド前"),
            Station("百合ヶ丘"),
            Station("新百合ヶ丘"),
            Station("柿生"),
            Station("鶴川"),
            Station("玉川学園前"),
            Station("町田"),
            Station("相模大野"),
            Station("小田急相模原"),
            Station("相武台前"),
            Station("座間"),
            Station("海老名"),
            Station("厚木"),
            Station("本厚木"),
            Station("愛甲石田"),
            Station("伊勢原"),
            Station("鶴巻温泉"),
            Station("東海大学前"),
            Station("秦野"),
            Station("渋沢"),
            Station("新松田"),
            Station("開成"),
            Station("栢山"),
            Station("富水"),
            Station("螢田"),
            Station("足柄"),
            Station("小田原"),
        )
    ),
    Line(
        lineName = "小田急電鉄 小田急江ノ島線",
        lineColor = Color(0xFF2288cc),
        stations = listOf(
            Station("相模大野"),
            Station("東林間"),
            Station("中央林間"),
            Station("南林間"),
            Station("鶴間"),
            Station("大和"),
            Station("桜ヶ丘"),
            Station("高座渋谷"),
            Station("長後"),
            Station("湘南台"),
            Station("六会日大前"),
            Station("善行"),
            Station("藤沢本町"),
            Station("藤沢"),
            Station("本鵠沼"),
            Station("鵠沼海岸"),
            Station("片瀬江ノ島"),
        )
    ),
    Line(
        lineName = "小田急電鉄 小田急多摩線",
        lineColor = Color(0xFF2288cc),
        stations = listOf(
            Station("新百合ヶ丘"),
            Station("五月台"),
            Station("栗平"),
            Station("黒川"),
            Station("はるひ野"),
            Station("小田急永山"),
            Station("小田急多摩センター"),
            Station("唐木田"),
        )
    ),
).sortedBy { it.lineName }
val seibuLines = listOf(
    Line(
        lineName = "西武鉄道 西武池袋線",
        lineColor = Color(0xFFff6600),
        stations = listOf(
            Station("池袋"),
            Station("椎名町"),
            Station("東長崎"),
            Station("江古田"),
            Station("桜台"),
            Station("練馬"),
            Station("中村橋"),
            Station("富士見台"),
            Station("練馬高野台"),
            Station("石神井公園"),
            Station("大泉学園"),
            Station("保谷"),
            Station("ひばりヶ丘"),
            Station("東久留米"),
            Station("清瀬"),
            Station("秋津"),
            Station("所沢"),
            Station("西所沢"),
            Station("小手指"),
            Station("狭山ヶ丘"),
            Station("武蔵藤沢"),
            Station("稲荷山公園"),
            Station("入間市"),
            Station("仏子"),
            Station("元加治"),
            Station("飯能"),
            Station("東飯能"),
            Station("高麗"),
            Station("武蔵横手"),
            Station("東吾野"),
            Station("吾野"),
        )
    ),
    Line(
        lineName = "西武鉄道 西武新宿線",
        lineColor = Color(0xFF0099cc),
        stations = listOf(
            Station("西武新宿"),
            Station("高田馬場"),
            Station("下落合"),
            Station("中井"),
            Station("新井薬師前"),
            Station("沼袋"),
            Station("野方"),
            Station("都立家政"),
            Station("鷺ノ宮"),
            Station("下井草"),
            Station("井荻"),
            Station("上井草"),
            Station("上石神井"),
            Station("武蔵関"),
            Station("東伏見"),
            Station("西武柳沢"),
            Station("田無"),
            Station("花小金井"),
            Station("小平"),
            Station("久米川"),
            Station("東村山"),
            Station("所沢"),
            Station("航空公園"),
            Station("新所沢"),
            Station("入曽"),
            Station("狭山市"),
            Station("新狭山"),
            Station("南大塚"),
            Station("本川越"),
        )
    ),
).sortedBy { it.lineName }
val tobuLines = listOf(
    Line(
        lineName = "東武鉄道 東武スカイツリーライン",
        lineColor = Color(0xFF0f6cc3),
        stations = listOf(
            Station("浅草"),
            Station("とうきょうスカイツリー"),
            Station("押上〈スカイツリー前〉"),
            Station("曳舟"),
            Station("東向島"),
            Station("鐘ヶ淵"),
            Station("堀切"),
            Station("牛田"),
            Station("北千住"),
            Station("小菅"),
            Station("五反野"),
            Station("梅島"),
            Station("西新井"),
            Station("竹ノ塚"),
            Station("谷塚"),
            Station("草加"),
            Station("獨協大学前〈草加松原〉"),
            Station("新田"),
            Station("蒲生"),
            Station("新越谷"),
            Station("越谷"),
            Station("北越谷"),
            Station("大袋"),
            Station("せんげん台"),
            Station("武里"),
            Station("一ノ割"),
            Station("春日部"),
            Station("北春日部"),
            Station("姫宮"),
            Station("東武動物公園"),
        )
    ),
    Line(
        lineName = "東武鉄道 東武伊勢崎線",
        lineColor = Color(0xFFff0000),
        stations = listOf(
            Station("東武動物公園"),
            Station("和戸"),
            Station("久喜"),
            Station("鷲宮"),
            Station("花崎"),
            Station("加須"),
            Station("南羽生"),
            Station("羽生"),
            Station("川俣"),
            Station("茂林寺前"),
            Station("館林"),
            Station("多々良"),
            Station("県"),
            Station("福居"),
            Station("東武和泉"),
            Station("足利市"),
            Station("野州山辺"),
            Station("韮川"),
            Station("太田"),
            Station("細谷"),
            Station("木崎"),
            Station("世良田"),
            Station("境町"),
            Station("剛志"),
            Station("新伊勢崎"),
            Station("伊勢崎"),
        )
    ),
).sortedBy { it.lineName }
val tokyuLines = listOf(
    Line(
        lineName = "東急電鉄 東横線",
        lineColor = Color(0xFFda0442),
        stations = listOf(
            Station("渋谷"),
            Station("代官山"),
            Station("中目黒"),
            Station("祐天寺"),
            Station("学芸大学"),
            Station("都立大学"),
            Station("自由が丘"),
            Station("田園調布"),
            Station("多摩川"),
            Station("新丸子"),
            Station("武蔵小杉"),
            Station("元住吉"),
            Station("日吉"),
            Station("綱島"),
            Station("大倉山"),
            Station("菊名"),
            Station("妙蓮寺"),
            Station("白楽"),
            Station("東白楽"),
            Station("反町"),
            Station("横浜"),
        )
    ),
    Line(
        lineName = "東急電鉄 目黒線",
        lineColor = Color(0xFF009cd2),
        stations = listOf(
            Station("目黒"),
            Station("不動前"),
            Station("武蔵小山"),
            Station("西小山"),
            Station("洗足"),
            Station("大岡山"),
            Station("奥沢"),
            Station("田園調布"),
            Station("多摩川"),
            Station("新丸子"),
            Station("武蔵小杉"),
            Station("元住吉"),
            Station("日吉"),
        )
    ),
    Line(
        lineName = "東急電鉄 田園都市線",
        lineColor = Color(0xFF20a288),
        stations = listOf(
            Station("渋谷"),
            Station("池尻大橋"),
            Station("三軒茶屋"),
            Station("駒沢大学"),
            Station("桜新町"),
            Station("用賀"),
            Station("二子玉川"),
            Station("二子新地"),
            Station("高津"),
            Station("溝の口"),
            Station("梶が谷"),
            Station("宮崎台"),
            Station("宮前平"),
            Station("鷺沼"),
            Station("たまプラーザ"),
            Station("あざみ野"),
            Station("江田"),
            Station("市が尾"),
            Station("藤が丘"),
            Station("青葉台"),
            Station("田奈"),
            Station("長津田"),
            Station("つくし野"),
            Station("すずかけ台"),
            Station("南町田グランベリーパーク"),
            Station("つきみ野"),
            Station("中央林間"),
        )
    ),
).sortedBy { it.lineName }
val keiseiLines = listOf(
    Line(
        lineName = "新京成電鉄 新京成線",
        lineColor = Color(0xFFef59a1),
        stations = listOf(
            Station("京成津田沼"),
            Station("新津田沼"),
            Station("前原"),
            Station("薬園台"),
            Station("習志野"),
            Station("北習志野"),
            Station("高根木戸"),
            Station("高根公団"),
            Station("滝不動"),
            Station("三咲"),
            Station("二和向台"),
            Station("鎌ヶ谷大仏"),
            Station("初富"),
            Station("新鎌ヶ谷"),
            Station("北初富"),
            Station("くぬぎ山"),
            Station("元山"),
            Station("五香"),
            Station("常盤平"),
            Station("八柱"),
            Station("みのり台"),
            Station("松戸新田"),
            Station("上本郷"),
            Station("松戸"),
        )
    ),
    Line(
        lineName = "京成電鉄 京成本線",
        lineColor = Color(0xFF005aaa),
        stations = listOf(
            Station("京成上野"),
            Station("日暮里"),
            Station("新三河島"),
            Station("町屋"),
            Station("千住大橋"),
            Station("京成関屋"),
            Station("堀切菖蒲園"),
            Station("お花茶屋"),
            Station("青砥"),
            Station("京成高砂"),
            Station("京成小岩"),
            Station("江戸川"),
            Station("国府台"),
            Station("市川真間"),
            Station("菅野"),
            Station("京成八幡"),
            Station("鬼越"),
            Station("京成中山"),
            Station("東中山"),
            Station("京成西船"),
            Station("海神"),
            Station("京成船橋"),
            Station("大神宮下"),
            Station("船橋競馬場"),
            Station("谷津"),
            Station("京成津田沼"),
            Station("京成大久保"),
            Station("実籾"),
            Station("八千代台"),
            Station("京成大和田"),
            Station("勝田台"),
            Station("志津"),
            Station("ユーカリが丘"),
            Station("京成臼井"),
            Station("京成佐倉"),
            Station("大佐倉"),
            Station("京成酒々井"),
            Station("宗吾参道"),
            Station("公津の杜"),
            Station("京成成田"),
            Station("東成田"),
            Station("空港第２ビル（第２旅客ターミナル）"),
            Station("成田空港（第１旅客ターミナル）"),
        )
    ),
).sortedBy { it.lineName }
val keikyuLines = listOf(
    Line(
        lineName = "京浜急行電鉄 京急本線",
        lineColor = Color(0xFF33c2e4),
        stations = listOf(
            Station("泉岳寺"),
            Station("品川"),
            Station("北品川"),
            Station("新馬場"),
            Station("青物横丁"),
            Station("鮫洲"),
            Station("立会川"),
            Station("大森海岸"),
            Station("平和島"),
            Station("大森町"),
            Station("梅屋敷"),
            Station("京急蒲田"),
            Station("雑色"),
            Station("六郷土手"),
            Station("京急川崎"),
            Station("八丁畷"),
            Station("鶴見市場"),
            Station("京急鶴見"),
            Station("花月総持寺"),
            Station("生麦"),
            Station("京急新子安"),
            Station("子安"),
            Station("神奈川新町"),
            Station("京急東神奈川"),
            Station("神奈川"),
            Station("横浜"),
            Station("戸部"),
            Station("日ノ出町"),
            Station("黄金町"),
            Station("南太田"),
            Station("井土ヶ谷"),
            Station("弘明寺"),
            Station("上大岡"),
            Station("屏風浦"),
            Station("杉田"),
            Station("京急富岡"),
            Station("能見台"),
            Station("金沢文庫"),
            Station("金沢八景"),
            Station("追浜"),
            Station("京急田浦"),
            Station("安針塚"),
            Station("逸見"),
            Station("汐入"),
            Station("横須賀中央"),
            Station("県立大学"),
            Station("堀ノ内"),
            Station("京急大津"),
            Station("馬堀海岸"),
            Station("浦賀"),
        )
    ),
    Line(
        lineName = "京浜急行電鉄 京急空港線",
        lineColor = Color(0xFF33c2e4),
        stations = listOf(
            Station("京急蒲田"),
            Station("糀谷"),
            Station("大鳥居"),
            Station("穴守稲荷"),
            Station("天空橋"),
            Station("羽田空港第3ターミナル"),
            Station("羽田空港第1・第2ターミナル"),
        )
    ),
).sortedBy { it.lineName }

// 地方鉄道
val chichibuTetsudoLines = listOf(
    //    秩父鉄道
    Line(
        lineName = "秩父鉄道 秩父本線",
        lineColor = Color.Blue,
        stations = listOf(
            Station("羽生"),
            Station("西羽生"),
            Station("新郷"),
            Station("武州荒木"),
            Station("東行田"),
            Station("行田市"),
            Station("持田"),
            Station("ソシオ流通センター"),
            Station("熊谷"),
            Station("上熊谷"),
            Station("石原"),
            Station("ひろせ野鳥の森"),
            Station("大麻生"),
            Station("明戸"),
            Station("武川"),
            Station("永田"),
            Station("ふかや花園"),
            Station("小前田"),
            Station("桜沢"),
            Station("寄居"),
            Station("波久礼"),
            Station("樋口"),
            Station("野上"),
            Station("長瀞"),
            Station("上長瀞"),
            Station("親鼻"),
            Station("皆野"),
            Station("和銅黒谷"),
            Station("大野原"),
            Station("秩父"),
            Station("御花畑"),
            Station("影森"),
            Station("浦山口"),
            Station("武州中川"),
            Station("武州日野"),
            Station("白久"),
            Station("三峰口"),
        )
    ),
).sortedBy { it.lineName }



val allLinesList = listOf(
//    JR
    jrHokkaidoLines, jrEastLines, jrTokaiLines, jrWestLines, jrShikokuLines, jrKyusyuLines,
//    首都圏地下鉄
    tokyoMetroLines, toeiChikatetsuLines,
//    大手私鉄
    keioLines, odakyuLines, seibuLines, keikyuLines, keiseiLines, tobuLines, tokyuLines,
//    その他
    chichibuTetsudoLines,
).flatten().distinct()