package com.prgckwb.stationquiz.game

val keioLine = Line(
    lineName = "京王線",
    stations = listOf(
        Station("新宿"),
        Station("笹塚"),
        Station("代田橋"),
        Station("明大前"),
        Station("下高井戸"),
        Station("桜上水"),
        Station("上北沢"),
        Station("八幡山"),
        Station("芦花公園"),
        Station("千歳烏山"),
        Station("仙川"),
        Station("つつじヶ丘"),
        Station("柴崎"),
        Station("国領"),
        Station("布田"),
        Station("調布"),
        Station("西調布"),
        Station("飛田給"),
        Station("武蔵野台"),
        Station("多磨霊園"),
        Station("東府中"),
        Station("府中"),
        Station("分倍河原"),
        Station("中河原"),
        Station("聖蹟桜ヶ丘"),
        Station("百草園"),
        Station("高幡不動"),
        Station("南平"),
        Station("平山城址公園"),
        Station("長沼"),
        Station("北野"),
        Station("京王八王子"),
    )
)

val odakyuLine = Line(
    lineName = "小田急線",
    stations = listOf(
        Station("新宿"),
        Station("南新宿"),
        Station("参宮橋"),
        Station("代々木八幡"),
        Station("代々木上原"),
        Station("東北沢"),
        Station("下北沢"),
        Station("世田谷代田"),
        Station("梅ヶ丘"),
        Station("豪徳寺"),
        Station("経堂"),
        Station("千歳船橋"),
        Station("祖師ヶ谷大蔵"),
        Station("成城学園前"),
        Station("喜多見"),
        Station("狛江"),
        Station("和泉多摩川"),
        Station("登戸"),
        Station("向ヶ丘遊園"),
        Station("生田"),
        Station("読売ランド前"),
        Station("百合ヶ丘"),
        Station("新百合ヶ丘"),
        Station("柿生"),
        Station("鶴川"),
        Station("玉川学園前"),
        Station("町田"),
        Station("相模大野"),
        Station("小田急相模原"),
        Station("相武台前"),
        Station("座間"),
        Station("海老名"),
        Station("厚木"),
        Station("本厚木"),
        Station("愛甲石田"),
        Station("伊勢原"),
        Station("鶴巻温泉"),
        Station("東海大学前"),
        Station("秦野"),
        Station("渋沢"),
        Station("新松田"),
        Station("開成"),
        Station("栢山"),
        Station("富水"),
        Station("螢田"),
        Station("足柄"),
        Station("小田原"),
    )
)

val takasakiLine = Line(
    lineName = "高崎線",
    stations = listOf(
        Station("上野"),
        Station("尾久"),
        Station("赤羽"),
        Station("浦和"),
        Station("さいたま新都心"),
        Station("大宮"),
        Station("宮原"),
        Station("上尾"),
        Station("北上尾"),
        Station("桶川"),
        Station("北本"),
        Station("鴻巣"),
        Station("北鴻巣"),
        Station("吹上"),
        Station("行田"),
        Station("熊谷"),
        Station("籠原"),
        Station("深谷"),
        Station("岡部"),
        Station("本庄"),
        Station("神保原"),
        Station("新町"),
        Station("倉賀野"),
        Station("高崎"),
    )
)

val tokyoMetroTosaiLine = Line(
    lineName = "東京メトロ東西線",
    stations = listOf(
        Station("中野"),
        Station("落合"),
        Station("高田馬場"),
        Station("早稲田"),
        Station("神楽坂"),
        Station("飯田橋"),
        Station("九段下"),
        Station("竹橋"),
        Station("大手町"),
        Station("日本橋"),
        Station("茅場町"),
        Station("門前仲町"),
        Station("木場"),
        Station("東陽町"),
        Station("南砂町"),
        Station("西葛西"),
        Station("葛西"),
        Station("浦安"),
        Station("南行徳"),
        Station("行徳"),
        Station("妙典"),
        Station("原木中山"),
        Station("西船橋"),
    )
)